(() => {
  'use strict';
  const P = window.FormPilotParser;
  const G = window.FormPilotGoogle;
  const root = document.getElementById('app');
  const modalRoot = document.getElementById('modal-root');
  const toastRoot = document.getElementById('toast-root');
  const TYPES = ['SHORT_ANSWER','PARAGRAPH','RADIO','CHECKBOX','DROP_DOWN','SCALE','DATE','TIME'];
  const TYPE_LABEL = {SHORT_ANSWER:'Short answer',PARAGRAPH:'Paragraph',RADIO:'Multiple choice',CHECKBOX:'Checkboxes',DROP_DOWN:'Dropdown',SCALE:'Linear scale',DATE:'Date',TIME:'Time'};
  const state = {
    form: load('formpilot_form', null),
    file: null,
    selectedSection: 0,
    selectedQuestion: 0,
    profile: G.getProfile(),
    published: load('formpilot_published', null),
    processing: false,
  };

  function load(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
  function saveForm() { if (state.form) localStorage.setItem('formpilot_form', JSON.stringify(state.form)); }
  function esc(v='') { return String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  function go(path) { location.hash = path; }
  function route() { return location.hash.slice(1) || '/'; }
  function btn(text, kind='primary', attrs='') { return `<button class="btn btn-${kind}" ${attrs}>${text}</button>`; }
  function logo() { return `<a class="logo" href="#/"><span class="logo-mark">F</span><span>FormPilot</span></a>`; }
  function countQuestions(form=state.form) { return form?.sections?.reduce((n,s)=>n+s.questions.length,0)||0; }
  function refreshStats() {
    if (!state.form) return;
    state.form.stats = {
      sections: state.form.sections.length,
      questions: countQuestions(),
      required: state.form.sections.flatMap(s=>s.questions).filter(q=>q.required).length,
    };
  }
  function toast(message, type='') {
    const el=document.createElement('div'); el.className=`toast ${type}`; el.textContent=message; toastRoot.appendChild(el);
    setTimeout(()=>el.remove(),4200);
  }
  function showError(error) { console.error(error); toast(error?.message || String(error), 'error'); }
  function setupModal(afterSave) {
    const origin=location.origin;
    modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-header"><div><span class="section-label">GOOGLE SETUP</span><h2>Connect Google Forms</h2></div><button class="modal-close" data-close>×</button></div>
      <p class="muted">FormPilot needs a Google OAuth Web Client ID. This public identifier enables the real account picker and Forms API consent screen. Do not enter a client secret.</p>
      <ol class="setup-steps"><li>Open Google Cloud Console and enable the Google Forms API.</li><li>Configure the OAuth consent screen and add your test users.</li><li>Create an OAuth Client ID for a <b>Web application</b>.</li><li>Add this Authorized JavaScript origin:<code class="code-value">${esc(origin)}</code></li></ol>
      <label class="field">OAuth Client ID<input id="client-id" placeholder="1234567890-abc.apps.googleusercontent.com" value="${esc(G.getClientId())}"></label>
      <div class="form-actions">${btn('Cancel','secondary','data-close')}${btn('Save and connect','primary','id="save-google"')}</div></div></div>`;
    modalRoot.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modalRoot.innerHTML='');
    modalRoot.querySelector('#save-google').onclick=async()=>{
      const value=modalRoot.querySelector('#client-id').value.trim();
      if(!/\.apps\.googleusercontent\.com$/.test(value)) return toast('Enter a valid Google OAuth Client ID.', 'error');
      G.setClientId(value); modalRoot.innerHTML='';
      try { await connectGoogle(); afterSave?.(); } catch(e){ showError(e); }
    };
  }
  async function connectGoogle() {
    if(!G.isConfigured()) return setupModal();
    state.profile=await G.connectForProfile(); render(); toast(`Connected as ${state.profile.email || state.profile.name}`, 'success');
  }
  function disconnectGoogle(){ G.disconnect(); state.profile=null; render(); toast('Google account disconnected.'); }

  function publicHeader(){
    const account=state.profile ? `<span class="account-chip">${esc(state.profile.email||state.profile.name)}</span>${btn('Dashboard','primary','data-go="/dashboard"')}` : `${btn('Sign in with Google','google','data-connect')}${btn('Start free','primary','data-go="/upload"')}`;
    return `<header class="site-header">${logo()}<nav class="site-nav"><a href="#features">Features</a><a href="#how">How it works</a><a href="#security">Security</a></nav><div class="header-actions">${account}</div></header>`;
  }
  function landing(){ return `${publicHeader()}<main>
    <section class="hero"><div><span class="eyebrow">DOCUMENT → GOOGLE FORM</span><h1>Turn real questionnaires into Google Forms</h1><p>Upload a Word, text-based PDF, or TXT questionnaire. FormPilot extracts the actual sections, questions, options, scales and required fields, then lets you review everything before publishing.</p><div class="hero-buttons">${btn('Convert a document →','primary','data-go="/upload"')}${btn('Download test document','secondary','data-sample')}</div><div class="trust-points"><span>✓ Real document parsing</span><span>✓ Google account consent</span><span>✓ Nothing publishes without approval</span></div></div>
      <div class="product-visual"><div class="visual-card upload-visual"><span class="file-tile">W</span><span class="file-tile pdf">PDF</span><span class="drop-mini">⇧ Upload document</span></div><div class="visual-card processing-visual"><b>Extracting your questionnaire…</b><div class="progress-track"><div class="progress-fill" style="width:76%"></div></div><p class="check-line">✓ Reading document text</p><p class="check-line">✓ Detecting sections and options</p><p class="muted small">○ Preparing editable review</p></div><div class="visual-card ready-visual"><b>Google Form ready for review</b><div class="mini-form"><span>1. What is your age?</span><span class="mini-line"></span><span>2. Select all services used</span><small>□ Online portal &nbsp; □ Email &nbsp; □ Office</small></div></div></div></section>
    <section class="audience"><span class="section-label">BUILT FOR QUESTIONNAIRE-HEAVY WORK</span><div class="audience-list"><span>Researchers</span><span>Universities</span><span>NGOs</span><span>Government teams</span><span>Schools</span><span>HR teams</span></div></section>
    <section id="how" class="public-section"><div class="section-heading"><span class="section-label">HOW IT WORKS</span><h2>Three controlled steps</h2><p>The app extracts; you decide what gets published.</p></div><div class="steps-grid">${[['⇧','Upload','Choose a DOCX, text-based PDF or TXT file.'],['✦','Review','Edit detected sections, types, options and required settings.'],['G','Publish','Select a Google account, grant consent and create the live Form.']].map((x,i)=>`<article class="step-card"><div class="icon-box">${x[0]}</div><span class="step-number">0${i+1}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></section>
    <section id="features" class="public-section features-section"><div class="section-heading"><span class="section-label">REAL FEATURES</span><h2>Built for useful first-pass conversion</h2></div><div class="features-grid">${[['DOCX','Mammoth extracts document text in your browser.'],['PDF','PDF.js reads selectable text page by page.'],['Types','Detects answers, choices, checkboxes, dates and scales.'],['Editor','Every generated item remains editable before publishing.'],['OAuth','Google Identity Services opens the real account picker.'],['Forms API','Creates, fills and publishes a genuine Google Form.']].map(x=>`<article class="feature-card"><div class="icon-box">${x[0][0]}</div><div><h3>${x[0]}</h3><p>${x[1]}</p></div></article>`).join('')}</div></section>
    <section id="security" class="showcase"><div class="showcase-copy"><span class="section-label">PRIVACY BY DESIGN</span><h2>Your document is parsed in the browser</h2><p>The uploaded file is not sent to our server. Form data goes to Google only after you press Publish and authorize access.</p><ul class="benefits"><li>✓ No client secret stored in the browser</li><li>✓ Short-lived Google access token</li><li>✓ Clear errors instead of fake success screens</li></ul>${btn('Try your questionnaire','primary','data-go="/upload"')}</div><div class="editor-demo"><div class="editor-demo-top"><b>Questionnaire review</b><span class="blue">Saved · Preview · Publish</span></div><div class="editor-demo-body"><aside class="editor-demo-sidebar"><b>Document outline</b><span>Section A · 6</span><span>Section B · 5</span><span>Needs review · 1</span></aside><div class="editor-demo-canvas"><h3>Section A: Respondent Details</h3><div class="mock-question"><span>1. Email address</span><small>Short answer</small></div><div class="mock-question"><span>2. Age group</span><small>Multiple choice</small></div><div class="mock-question"><span>3. Date of response</span><small>Date</small></div></div></div></div></section>
    <section class="dark-cta"><h2>Test the complete flow</h2><p>Upload your own questionnaire, review the extracted content, then connect Google when you are ready to publish.</p>${btn('Start conversion →','primary','data-go="/upload"')}</section></main>${footer()}`; }
  function footer(){ return `<footer class="site-footer"><div>${logo()}<p>Documents in. Google Forms out.</p></div><div class="footer-column"><b>Product</b><a href="#features">Features</a><a href="#how">How it works</a></div><div class="footer-column"><b>Resources</b><a data-sample>Test document</a><a href="https://github.com/ryanair000/formgen" target="_blank" rel="noopener">GitHub</a></div><div class="footer-column"><b>Google</b><a data-go="/settings">OAuth setup</a><a href="https://developers.google.com/forms/api" target="_blank" rel="noopener">Forms API</a></div></footer>`; }

  function shell(title, body, active=''){ const account=state.profile ? `<span class="account-chip">${esc(state.profile.email||state.profile.name)}</span>` : btn('Connect Google','google','data-connect'); return `<div class="app-shell"><aside class="app-sidebar">${logo()}<nav class="app-nav"><button class="${active==='dashboard'?'active':''}" data-go="/dashboard">▣ Overview</button><button class="${active==='upload'?'active':''}" data-go="/upload">＋ New conversion</button><button class="${active==='settings'?'active':''}" data-go="/settings">⚙ Google setup</button></nav><div class="sidebar-bottom"><div class="plan-card"><b>Browser-first MVP</b><p class="muted small">DOCX · PDF · TXT · Google Forms</p></div></div></aside><div class="app-main"><header class="app-topbar"><h1>${esc(title)}</h1><div class="header-actions">${account}</div></header><main class="app-content">${body}</main></div></div>`; }
  function dashboard(){ const q=countQuestions(); return shell('Overview', `<section class="welcome-card"><div><span class="section-label">FORMPILOT WORKSPACE</span><h2>${state.form?'Continue your questionnaire':'Convert your first document'}</h2><p class="muted">${state.form?`${esc(state.form.title)} has ${q} detected questions.`:'Upload a questionnaire to create an editable review draft.'}</p></div>${btn(state.form?'Continue review':'New conversion →','primary',`data-go="${state.form?'/review':'/upload'}"`)}</section><div class="stats-grid"><div class="stat-card"><b>${state.form?.stats?.sections||0}</b><span>Sections detected</span></div><div class="stat-card"><b>${q}</b><span>Questions detected</span></div><div class="stat-card"><b>${state.form?.stats?.required||0}</b><span>Required questions</span></div><div class="stat-card"><b>${state.profile?'Yes':'No'}</b><span>Google connected</span></div></div><section class="panel"><div class="panel-head"><h3>Current project</h3>${state.form?btn('Delete','danger','data-delete-project'):''}</div>${state.form?`<div class="project-row" data-go="/review"><span class="project-icon">▣</span><div><b>${esc(state.form.title)}</b><p class="muted small">${q} questions · ${state.form.sections.length} sections</p></div><span class="status-pill">Review draft</span><span>${state.form.fileName?esc(state.form.fileName):'Saved locally'}</span></div>`:`<div class="empty-state"><h3>No questionnaire yet</h3><p class="muted">Start with the provided sample or upload your own document.</p><div class="header-actions">${btn('Upload document','primary','data-go="/upload"')}${btn('Download sample','secondary','data-sample')}</div></div>`}</section>`, 'dashboard'); }

  function upload(){ return shell('New conversion', `<div class="narrow"><section class="upload-panel"><div class="upload-heading"><span class="section-label">REAL DOCUMENT PARSING</span><h2>Create a form from your questionnaire</h2><p>DOCX and TXT work directly. PDFs must contain selectable text; scanned image PDFs need OCR and will show a clear error.</p></div><label class="big-drop" id="drop-zone"><input id="file-input" type="file" accept=".docx,.pdf,.txt"><span class="upload-icon">⇧</span><b id="file-label">Drag and drop or click to choose a document</b><span class="muted" id="file-meta">DOCX, PDF or TXT · Maximum 20 MB</span></label><div class="form-grid"><label class="field">Document language<select id="language"><option>Auto-detect</option><option>English</option><option>Kiswahili</option></select></label><label class="field">Form purpose<select id="purpose"><option>Survey</option><option>Quiz</option><option>Registration</option><option>Application</option></select></label></div><div class="warning-box"><b>Before publishing:</b> Google will ask you to select an account and grant FormPilot permission to create and edit the form.</div><div class="form-actions">${btn('Download sample','secondary','data-sample')}${btn('Process document →','primary','id="process-file" disabled')}</div></section></div>`, 'upload'); }

  async function processFile(){ if(!state.file) return; state.processing=true; go('/processing'); render(); const steps=['Uploading document','Reading document text','Detecting sections and questions','Identifying question types','Preparing review']; try { for(let i=0;i<2;i++){ setProgress(steps[i],(i+1)*15,i); await wait(180); } const result=await P.parseFile(state.file); result.fileName=state.file.name; result.purpose=document.getElementById('purpose')?.value||'Survey'; state.form=result; refreshStats(); saveForm(); for(let i=2;i<steps.length;i++){ setProgress(steps[i],55+(i-2)*20,i); await wait(160); } toast(`Extracted ${result.stats.questions} questions from ${state.file.name}.`,'success'); go('/review'); } catch(e){ state.processing=false; localStorage.setItem('formpilot_last_error',e.message); go('/upload'); showError(e); } }
  function wait(ms){ return new Promise(r=>setTimeout(r,ms)); }
  function setProgress(label,pct,done){ const bar=document.querySelector('.progress-fill'); const text=document.getElementById('progress-text'); if(bar)bar.style.width=`${pct}%`; if(text)text.textContent=label; document.querySelectorAll('.processing-steps li').forEach((li,i)=>li.classList.toggle('done',i<=done)); }
  function processing(){ return shell('Processing', `<section class="processing-card"><div class="icon-box center">✦</div><h2>Reading your document</h2><p class="muted" id="progress-text">Preparing parser…</p><div class="progress-track"><div class="progress-fill" style="width:5%"></div></div><ol class="processing-steps"><li>Uploading document</li><li>Reading document text</li><li>Detecting sections and questions</li><li>Identifying question types</li><li>Preparing review</li></ol><p class="muted small">Keep this tab open while the file is processed locally.</p></section>`, 'upload'); }

  function current(){ const s=state.form?.sections?.[state.selectedSection]; const q=s?.questions?.[state.selectedQuestion]; return {s,q}; }
  function questionPreview(q){ if(q.options?.length) return q.options.map(o=>`<label class="choice-row"><input type="${q.type==='CHECKBOX'?'checkbox':'radio'}" disabled> ${esc(o)}</label>`).join(''); if(q.type==='PARAGRAPH')return '<textarea disabled placeholder="Long answer text"></textarea>'; if(q.type==='DATE')return '<input type="date" disabled>'; if(q.type==='TIME')return '<input type="time" disabled>'; if(q.type==='SCALE')return `<div class="scale-preview">${Array.from({length:(q.scale?.high||5)-(q.scale?.low||1)+1},(_,i)=>`<span>${(q.scale?.low||1)+i}</span>`).join('')}</div>`; return '<input disabled placeholder="Short answer text">'; }
  function review(){ if(!state.form)return shell('Review','<div class="empty-state"><h2>No form to review</h2>'+btn('Upload document','primary','data-go="/upload"')+'</div>'); const {s,q}=current(); return `<div class="review-app"><header class="review-topbar"><button class="btn btn-ghost" data-go="/dashboard">←</button><div><b>${esc(state.form.title)}</b><p class="muted small">${countQuestions()} questions · saved in this browser</p></div><div class="top-actions">${btn('Preview','secondary','data-go="/preview"')}${btn(state.profile?'Publish to Google Forms':'Connect & publish','primary','data-publish')}</div></header><div class="review-body"><aside class="outline-panel"><h3>Document outline</h3>${state.form.sections.map((x,i)=>`<button class="outline-button ${i===state.selectedSection?'active':''}" data-section="${i}"><span>${esc(x.title)}</span><b>${x.questions.length}</b></button>`).join('')}<button class="outline-button" data-add-section>＋ Add section</button></aside><main class="review-canvas"><div class="canvas-heading"><div><h2>${esc(s.title)}</h2><p class="muted">${s.questions.length} questions</p></div>${btn('＋ Add question','secondary','data-add-question')}</div>${s.questions.map((x,i)=>`<article class="question-card ${i===state.selectedQuestion?'selected':''}" data-question="${i}"><div class="question-header"><span class="question-number">${i+1}</span><div><b class="question-title">${esc(x.title)}</b>${x.description?`<p class="muted small">${esc(x.description)}</p>`:''}</div>${x.warning?`<span class="review-warning">Check logic</span>`:''}</div><div class="answer-preview">${questionPreview(x)}</div></article>`).join('')||'<div class="empty-state"><p>No questions in this section.</p></div>'}</main><aside class="properties-panel">${q?properties(q):'<p class="muted">Select a question to edit it.</p>'}</aside></div></div>`; }
  function properties(q){ return `<div class="property-section"><h3>Question settings</h3><label class="field">Question title<textarea id="q-title">${esc(q.title)}</textarea></label><label class="field">Question type<select id="q-type">${TYPES.map(t=>`<option value="${t}" ${q.type===t?'selected':''}>${TYPE_LABEL[t]}</option>`).join('')}</select></label><label class="inline-toggle">Required<input id="q-required" type="checkbox" ${q.required?'checked':''}></label></div>${['RADIO','CHECKBOX','DROP_DOWN'].includes(q.type)?`<div class="property-section"><div class="panel-head"><h3>Options</h3>${btn('＋','secondary','data-add-option')}</div><div class="option-editor">${q.options.map((o,i)=>`<div class="option-line"><input data-option="${i}" value="${esc(o)}"><button class="btn btn-danger btn-sm" data-remove-option="${i}">×</button></div>`).join('')}</div></div>`:''}<div class="property-section"><div class="confidence"><b>✓ Parsed from your uploaded document</b><br>Review this item before publishing.</div>${btn('Delete question','danger','data-delete-question')}</div>`; }

  function preview(){ if(!state.form)return dashboard(); return shell('Form preview', `<div class="preview-toolbar">${btn('← Back to editor','secondary','data-go="/review"')}${btn(state.profile?'Publish to Google Forms':'Connect & publish','primary','data-publish')}</div><article class="preview-paper"><div class="preview-accent"></div><h1>${esc(state.form.title)}</h1>${state.form.description?`<p class="muted">${esc(state.form.description)}</p>`:''}<small class="muted">* Required</small>${state.form.sections.map(s=>`<section class="preview-section"><h2>${esc(s.title)}</h2>${s.description?`<p class="muted">${esc(s.description)}</p>`:''}${s.questions.map(q=>`<div class="preview-question"><b>${esc(q.title)} ${q.required?'<span class="required-star">*</span>':''}</b>${q.description?`<small class="muted">${esc(q.description)}</small>`:''}${questionPreview(q)}</div>`).join('')}</section>`).join('')}</article>`, ''); }

  async function publish(){ if(!state.form)return; if(!G.isConfigured()){ setupModal(()=>publish()); return; } go('/publishing'); render(); try { state.published=await G.publishForm(state.form,(label,pct)=>setPublishProgress(label,pct)); localStorage.setItem('formpilot_published',JSON.stringify(state.published)); state.profile=G.getProfile()||state.profile; go('/success'); } catch(e){ localStorage.setItem('formpilot_publish_error',e.message); go('/review'); showError(e); } }
  function setPublishProgress(label,pct){ const t=document.getElementById('publish-label'),b=document.querySelector('.publish-progress .progress-fill'); if(t)t.textContent=label;if(b)b.style.width=`${pct}%`; }
  function publishing(){ return shell('Publishing', `<section class="processing-card"><div class="icon-box center">G</div><h2>Creating your Google Form</h2><p class="muted" id="publish-label">Opening Google authorization…</p><div class="publish-progress"><div class="progress-track"><div class="progress-fill" style="width:5%"></div></div></div><p class="muted small">Do not close the Google consent popup.</p></section>`); }
  function success(){ const p=state.published; if(!p)return dashboard(); return shell('Published', `<section class="success-card"><div class="success-mark">✓</div><h2>Your Google Form is live</h2><p class="muted">The form was created in the Google account you authorized and is accepting responses.</p><div class="link-box"><span class="link-value">${esc(p.responderUri)}</span>${btn('Copy','primary','data-copy-link')}</div><div class="header-actions center-actions"><a class="btn btn-primary" href="${esc(p.responderUri)}" target="_blank" rel="noopener">Open respondent form</a><a class="btn btn-secondary" href="${esc(p.editUri)}" target="_blank" rel="noopener">Edit in Google Forms</a></div><p>${btn('Return to dashboard','ghost','data-go="/dashboard"')}</p></section>`); }

  function settings(){ const origin=location.origin; return shell('Google setup', `<section class="panel settings-card"><span class="section-label">GOOGLE CLOUD</span><h2>OAuth and Forms API setup</h2><p class="muted">A Google OAuth Client ID is required because forms are created inside each user’s own Google account.</p><ol class="setup-steps"><li>Enable Google Forms API in Google Cloud Console.</li><li>Configure OAuth consent and add test users.</li><li>Create a Web application OAuth Client ID.</li><li>Add <code class="code-value">${esc(origin)}</code> as an Authorized JavaScript origin.</li></ol><label class="field">OAuth Client ID<input id="settings-client-id" value="${esc(G.getClientId())}" placeholder="1234567890-abc.apps.googleusercontent.com"></label><div class="form-actions">${btn('Save Client ID','primary','data-save-client')}${state.profile?btn('Disconnect Google','danger','data-disconnect'):btn('Sign in with Google','google','data-connect')}</div>${state.profile?`<div class="success-box"><b>Connected:</b> ${esc(state.profile.email||state.profile.name)}</div>`:`<div class="warning-box">Not connected. After saving the Client ID, press Sign in with Google to verify the account picker.</div>`}</section>`, 'settings'); }

  function render(){ const r=route(); root.innerHTML = r==='/'?landing():r==='/dashboard'?dashboard():r==='/upload'?upload():r==='/processing'?processing():r==='/review'?review():r==='/preview'?preview():r==='/publishing'?publishing():r==='/success'?success():r==='/settings'?settings():landing(); bind(); window.scrollTo(0,0); }
  function bind(){
    root.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));
    root.querySelectorAll('[data-connect]').forEach(x=>x.onclick=()=>connectGoogle().catch(showError));
    root.querySelectorAll('[data-sample]').forEach(x=>x.onclick=()=>{ const a=document.createElement('a');a.href='./samples/FormPilot_Test_Questionnaire.txt';a.download='FormPilot_Test_Questionnaire.txt';a.click(); });
    root.querySelectorAll('[data-publish]').forEach(x=>x.onclick=publish);
    root.querySelector('[data-disconnect]')?.addEventListener('click',disconnectGoogle);
    root.querySelector('[data-save-client]')?.addEventListener('click',()=>{ const v=document.getElementById('settings-client-id').value.trim(); if(v&&!/\.apps\.googleusercontent\.com$/.test(v))return toast('Enter a valid Google OAuth Client ID.','error');G.setClientId(v);toast('Google Client ID saved.','success');render(); });
    root.querySelector('[data-delete-project]')?.addEventListener('click',()=>{ if(confirm('Delete the local project?')){state.form=null;localStorage.removeItem('formpilot_form');render();} });
    root.querySelector('[data-copy-link]')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(state.published.responderUri);toast('Responder link copied.','success');});
    const fileInput=document.getElementById('file-input'), drop=document.getElementById('drop-zone');
    if(fileInput){ const choose=f=>{ if(!f)return;if(f.size>20*1024*1024)return toast('File is larger than 20 MB.','error');state.file=f;document.getElementById('file-label').textContent=f.name;document.getElementById('file-meta').textContent=`${(f.size/1024).toFixed(1)} KB · ready`;document.getElementById('process-file').disabled=false;}; fileInput.onchange=e=>choose(e.target.files[0]); drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');choose(e.dataTransfer.files[0])};document.getElementById('process-file').onclick=processFile; }
    root.querySelectorAll('[data-section]').forEach(x=>x.onclick=()=>{state.selectedSection=Number(x.dataset.section);state.selectedQuestion=0;render()});
    root.querySelectorAll('[data-question]').forEach(x=>x.onclick=()=>{state.selectedQuestion=Number(x.dataset.question);render()});
    root.querySelector('[data-add-section]')?.addEventListener('click',()=>{state.form.sections.push({id:`section_${Date.now()}`,title:'New section',description:'',questions:[]});state.selectedSection=state.form.sections.length-1;state.selectedQuestion=0;refreshStats();saveForm();render()});
    root.querySelector('[data-add-question]')?.addEventListener('click',()=>{const s=state.form.sections[state.selectedSection];s.questions.push({id:`q_${Date.now()}`,title:'New question',description:'',type:'SHORT_ANSWER',required:false,options:[],scale:null});state.selectedQuestion=s.questions.length-1;refreshStats();saveForm();render()});
    const {q}=current(); if(q){ const title=document.getElementById('q-title'),type=document.getElementById('q-type'),req=document.getElementById('q-required'); title.oninput=e=>{q.title=e.target.value;saveForm()}; type.onchange=e=>{q.type=e.target.value;if(['RADIO','CHECKBOX','DROP_DOWN'].includes(q.type)&&!q.options.length)q.options=['Option 1','Option 2'];saveForm();render()};req.onchange=e=>{q.required=e.target.checked;refreshStats();saveForm()};root.querySelectorAll('[data-option]').forEach(x=>x.oninput=e=>{q.options[Number(x.dataset.option)]=e.target.value;saveForm()});root.querySelectorAll('[data-remove-option]').forEach(x=>x.onclick=()=>{q.options.splice(Number(x.dataset.removeOption),1);saveForm();render()});root.querySelector('[data-add-option]')?.addEventListener('click',()=>{q.options.push(`Option ${q.options.length+1}`);saveForm();render()});root.querySelector('[data-delete-question]')?.addEventListener('click',()=>{state.form.sections[state.selectedSection].questions.splice(state.selectedQuestion,1);state.selectedQuestion=Math.max(0,state.selectedQuestion-1);refreshStats();saveForm();render()}); }
  }
  window.addEventListener('hashchange',render);
  render();
})();
